console.log(parseInt(10.5));				
console.log(parseInt('10.5'));				
console.log(parseInt('123abc.456'));		
console.log(parseInt(true));					
console.log(parseInt(null));					
console.log(parseInt(10, 2));					
console.log(parseInt(20, 8)); 				
console.log(parseInt(20, 16)); 		
console.log(parseFloat('2.5'));				
console.log(parseFloat('567.89'));			
console.log(parseFloat('123.4abc5'));	
console.log(parseFloat(true));				
console.log(parseFloat(false));				
console.log(parseFloat(null));				
console.log(encodeURI('http://me.org/?x=a b'));	
console.log(decodeURI('http://me.org/?x=a%20b'));
console.log(encodeURI('http://')); 
console.log(encodeURIComponent('http://')); 
console.log(decodeURIComponent('http%3A%2F%2F'));